name: Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  publish:
    name: Publish to Github Package Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Run npm ci
        env:
          CI: true
        run: npm ci

      - name: Publish package
        if: success()
        env:
          CI: true
          GITHUB_TOKEN: ${{ github.token }}
        run: npx semantic-release
